Lesson3  with focus
aigul-ermak/ts-project pull request #7
Opened 2022-04-28 02:47 UTC by aigul-ermak

2022-04-28 04:55 UTC, andrey-kudinov requested changes
Пж попробуйте ещё поработать с доступностью с учётом комментариев и сообщений в Телеграме

2022-04-28 04:55 UTC, andrey-kudinov commented on src/modals/tabs.ts
> +        const isTabPressed = e.keyCode === 9 || e.keyCode === 'Tab'
Табы - это дефолтное поведение браузера, не нужно отдельно вешать на них события

2022-04-28 04:55 UTC, andrey-kudinov commented on src/modals/modals.ts
> +                // добавила атрибут tabindex="0" в класс модалки .popup_engineer_btn
Не увидел в этом ПР добавление tabindex в HTML
Этот атрибут нужен для элементов у которых по дефолту нет взаимодействия с табами
Например div или span

2022-04-28 05:01 UTC, andrey-kudinov commented on src/modals/modals.ts
> +                //при двойном(?) нажатии на tab - появляется фокус
Это сработает с любой из модалок на сайте?
Я думаю двойное нажатие - это не то что ожидает пользователь
Элемент текущей модалка должен быть в фокусе и у пользователя не должно быть сомнений где находится его фокус

2022-04-30 05:40 UTC, andrey-kudinov requested changes
Здесь всё выглядит хорошо
Но много изменений из другого ПР
Вы можете закрыть другие ПР если там всё в порядке, тогда здесь будет меньше изменений
На данный момент их много и они отвлекают от главного

2022-04-30 05:40 UTC, andrey-kudinov commented on dist/script.js
> +/***/ }),
Пж не добавляй дист в репозиторий

2022-04-30 05:40 UTC, andrey-kudinov commented on src/modals/modals.ts
> +                           closeClickOverlay = true,
Вот этот участок точно отработает? Тут же сокращенная запись объектов

2022-04-30 05:40 UTC, andrey-kudinov commented on src/modals/modals.ts
> +                           closeClickOverlay = true,
Да, думаю отработает как надо

2022-05-01 00:45 UTC, aigul-ermak commented on src/modals/tabs.ts
> +        const isTabPressed = e.keyCode === 9 || e.keyCode === 'Tab'
ok

2022-05-01 00:46 UTC, aigul-ermak commented on src/modals/modals.ts
> +                           closeClickOverlay = true,
вроде работает

2022-05-01 00:47 UTC, aigul-ermak commented on dist/script.js
> +/***/ }),
при коммите я снимаю галочки со всех фалов с репозитория dist, пропускаю возможно((

2022-05-01 00:57 UTC, merged